### ISSUE TITLE
Documentation Pass

### ISSUE THREAD

**Issue by vegu** [20c/django-handleref#16]
Currently all of the documentation we have is in the readme file. They should be moved to a /docs directory

- [x] make a /docs directory
- [x] quickstart.md with install instructions and example
- [x] examples.md with rest of examples
- [x] mkdocs configuration
- [x] github workflow to generate documentation to gh-pages
- [x] add /docs/api directory and use `pymdgen` to autogenerate api docs
  - https://github.com/20c/confu/tree/main/docs/api for examples on how to set that up

**Comment by jason20c** [comment]
Added documentation for APIs except for models.py as that is giving an error.
