### ISSUE TITLE
handleref tries to update version field on every model under reversion control

### ISSUE THREAD

**Issue by ercpe** [20c/django-handleref#38]
Hi,

we're in the process of integrating a library that depends on django-handleref in our application. Our application already uses django-reversion and most of our models are under control of reversion.

Our test suite now failes because handleref tries to update the `version` field on every model under reversion control. The cause is the `post_revision_commit` signal handler in https://github.com/20c/django-handleref/blob/main/src/django_handleref/models.py#L13.

The handler should perform an `isinstance(vs.object, HandleRefModel)` before updating the `version` field.

**Comment by ercpe** [comment]
See https://github.com/20c/django-handleref/pull/39

**Comment by vegu** [comment]
@ercpe thanks, seems like an oversight and fix makes sense to me
